### ISSUE TITLE
WhoAmI and all power platform tasks show unknown error

### ISSUE THREAD

**Issue by dharmidharmu** [microsoft/powerplatform-actions#172] opened 2022-02-02 11:37 UTC
All the microsoft power platform Tasks are not working.

**Comment by atfagi** [comment] 2022-02-02 15:08
Same here, getting error "failed: spawn UNKNOWN" sice a a few days.

![image](https://user-images.githubusercontent.com/73284434/152180500-7170c9ea-f1e4-4ee7-bf91-f2fbf29120bb.png)

Any suggestions for fixing?

**Comment by dharmidharmu** [comment] 2022-02-02 15:11
@atfagi no updates till now. All microsoft power platform tasks are not working!! No fix for this.

**Comment by damiaanh** [comment] 2022-02-02 15:34
Yes, we are experiencing these issues as well.

**Comment by dharmidharmu** [comment] 2022-02-02 15:37
@damiaanh I think it will be resolved soon. Since it's a major issue

**Comment by rajyraman** [comment] 2022-02-03 23:46
@davidjenni - I am also getting the same error. Tried different versions from 0.4.0 to latest, but the error is same. Tried in ubuntu-latest and windows-latest as well, but no change.

**Comment by VG-CoE-QA** [comment] 2022-02-04 11:02
The same errors for me, please help!

**Comment by dharmidharmu** [comment] 2022-02-04 11:04
@VG-CoE-QA  I'm also waiting for this issue to be fixed

**Comment by fabiocaloretbext** [comment] 2022-02-04 12:41
Same error

**Comment by jfabre-cit** [comment] 2022-02-04 14:38
Same error here

**Comment by Gabrinator** [comment] 2022-02-04 15:47
It fails for me as well. However, I'm able to connect and perform all actions successfully through the Power Platform CLI. 

Definitely hoping this gets resolved soon.

**Comment by dharmidharmu** [comment] 2022-02-04 16:06
@Gabrinator  can you share the code so that we can use it

**Comment by Gabrinator** [comment] 2022-02-04 21:23
@dharmidharmu I don't have code per say.  I installed the [Power Apps CLI for VSCode](https://powerapps.microsoft.com/en-us/blog/power-platform-extension-for-vs-code/) and then used 
`pac solution export` to export the solution from my dev
`pac solution unpack` to unpack the solution and check the files into source control
`pac solution import` to import in the downstream environment
See documentation [here](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/cli/reference/solution-command)

Hope that helps.

**Comment by taimoor-hotiana-bzy** [comment] 2022-02-05 02:32
I wish I had seen this earlier before spend an all nighter trying to troubleshoot. Please HELP our CI/CD completely stopped working. Getting the errors below.
![error](https://user-images.githubusercontent.com/74422979/152625633-8652bf41-da0b-4ab9-af2e-6af68e4f953c.PNG)
![error1](https://user-images.githubusercontent.com/74422979/152625640-6a206cd6-0c0b-4c79-8715-06e704fe8af0.PNG)

**Comment by dharmidharmu** [comment] 2022-02-05 02:40
@taimoor-hotiana-bzy I'm also trying but nothing works

**Comment by sync** [comment] 2022-02-06 00:02
similar situation here

**Comment by kkanakas** [comment] 2022-02-06 04:56
Hey folks, I am the PM of Power Platform Developer tools, we are aware of the issue and are working on fixing it.

**Comment by kkanakas** [comment] 2022-02-06 23:44
Hey folks, the team has narrowed down the cause of this issue, we are working with the GitHub team towards a resolution.  I will provide an update on the fix tomorrow.

**Comment by MattB-msft** [comment] 2022-02-07 01:42
Closing this thread and will comment in master thread.

**Closed by MattB-msft** 2022-02-07 01:42 UTC
